### ISSUE TITLE
Missing cpp files?

### ISSUE THREAD

**Issue by micis** [veyesys/h5stream#1]
Hello,

I've tried to compile h5stream on Linux without success.
It seems like it does not build the h5slib:
`/usr/bin/ld: cannot find -lh5slib`

Folder _h5slib/_ does not contain neither _cpp_ files nor _Makefile_.
But it contains unneeded precompiled files like `h5slib/output/Release/h5slib.dll`

Or may I miss a git submodule?

I can provide more logs if needed.

Thanks for your attention!

**Comment by xsmart** [comment]
Yes, need buy the license to get all the source code.

**Comment by jjailbird** [comment]
Which license should I purchase? 
RapidVMS or RapidONVIF?

**Comment by xsmart** [comment]
support@veyesys.com for more license question.
